-- Blue Book 2025 v3.6 offense catalog (Section 4, pp. 21–24)
-- Generated by scripts/generate_blue_book_offenses.py — re-run script to regenerate.

BEGIN;

-- Natural key for idempotent upserts
CREATE UNIQUE INDEX IF NOT EXISTS offense_types_group_name_policy_category_key
  ON public.offense_types (offense_group, offense_name, policy_category);

INSERT INTO public.offense_types (
  id, offense_group, offense_name, offense_code, demerits, policy_category
)
VALUES
  ('17a28544-c2e2-5445-83d9-a4ab3ad1af75', 'Appearance', 'In need of a shave or haircut', '1', 3, 1),
  ('f7c6cc59-606c-5a33-b8e2-c7f6f8bde97d', 'Appearance', 'Out of uniform', '1', 3, 1),
  ('98853bd8-635c-59f8-a7f5-4649ee2c9f59', 'Appearance', 'Unauthorized uniform', '1', 3, 1),
  ('9858682a-47aa-565b-9b6a-8e0245aaf2cb', 'Appearance', 'Hands in pockets', '1', 3, 1),
  ('ed185f1c-fbc3-51df-a6b4-9ac6a17af619', 'Appearance', 'Unclean uniform', '1', 3, 1),
  ('565677c8-4212-5d77-a3e6-d4aaf28fe97f', 'Appearance', 'In need of repair (uniform)', '1', 3, 1),
  ('de51bef2-bd50-536e-93f7-1f9d9c819bb6', 'Appearance', 'Improper fitting uniform', '1', 3, 1),
  ('3f851e4c-5188-559d-8fb9-1b799d5bd2c4', 'Appearance', 'Improper wearing of hat, pants, etc.', '1', 3, 1),
  ('fa385c52-9c4d-5477-be3f-2d1ba690445f', 'Arms (Rifle/Sabre)', 'Unattended', '1', 3, 1),
  ('e57cf788-fa8d-5429-984d-1943ba6e4343', 'Behavior in Class', 'Failure to comply', '1', 3, 1),
  ('9aa2bbff-e02c-5575-8181-e172f763f635', 'Behavior in Class', 'Late assignment submission', '1', 3, 1),
  ('3da86105-6f32-5511-9d5a-9a40a7615c66', 'Behavior in Class', 'Reading/viewing unauthorized materials', '1', 3, 1),
  ('3d84b410-428f-5635-a8a7-75fa1bcaebf0', 'Behavior in Class', 'Talking out of turn', '1', 3, 1),
  ('7ad8c40c-629a-5d29-92dc-375e90515b97', 'Campus', 'Eating food outside of designated meal areas', '1', 3, 1),
  ('6666af96-20a5-51d1-8c5d-2e7ba2e390de', 'Campus', 'Overdue library book', '1', 3, 1),
  ('795ffa63-1526-5b30-9fda-6979013fd660', 'Conduct', 'Cutting in line', '1', 3, 1),
  ('e15aae28-28cb-5f7d-b262-6bfcbfb1e10d', 'Conduct', 'Failure to comply', '1', 3, 1),
  ('9e42acb9-d391-5161-8a48-145d77666f9b', 'Conduct', 'Failure to salute', '1', 3, 1),
  ('ae3cf525-4a8e-5445-ae97-70e9d541ac24', 'Conduct', 'Gear adrift', '1', 3, 1),
  ('5920e46a-2383-5d44-806b-466151884f10', 'Conduct', 'Late to any required activity', '1', 3, 1),
  ('7fef26f1-33de-5a80-8040-2c1eda710d95', 'Conduct', 'Talking while at-ease', '1', 3, 1),
  ('5894cbef-679f-56a1-a6ef-27a76672b7a3', 'Conduct', 'Unnecessary comments', '1', 3, 1),
  ('706eda6e-03e7-5ab1-8ce1-bcf6e8531a9d', 'Conduct', 'Running in non-athletic uniform', '1', 3, 1),
  ('c2f7d725-2e6d-5f81-b6b5-8c3d0488f0f2', 'Room/Barracks', 'Door/Bed covering', '1', 3, 1),
  ('9984e76d-78d4-5ec0-93a9-cc285f9aba3b', 'Room/Barracks', 'Room in disorder', '1', 3, 1),
  ('59c49c79-187f-5987-af1e-1632670dccff', 'Room/Barracks', 'Talking out of window', '1', 3, 1),
  ('831e5ab4-2ce0-54fe-8846-ad206e42fae3', 'Room/Barracks', 'Too many cadets in room (4 maximum)', '1', 3, 1),
  ('4f59bb5a-9f4e-5743-9da4-a6987520d2bf', 'Room/Barracks', 'Unprepared for check off/inspection', '1', 3, 1),
  ('1c3bdb9e-b30b-56f7-a113-de4bfc271813', 'When in Ranks', 'Chewing gum', '1', 3, 1),
  ('71293be9-bad5-5eac-b55a-8ec48cc0bf9d', 'When in Ranks', 'Eating', '1', 3, 1),
  ('a8ddeaea-e205-536a-85c7-590b678897a2', 'When in Ranks', 'Inattention', '1', 3, 1),
  ('fd9d6de4-62d6-514d-8a0f-12f48a105f9f', 'When in Ranks', 'Moving', '1', 3, 1),
  ('eedb3b2f-275e-5dcc-893e-c0e580ce50b8', 'When in Ranks', 'Talking', '1', 3, 1),
  ('dcbc840b-590b-5e7b-bf3c-37610e4ced40', 'Behavior in Class', 'Failure to do assignment', '2a', 6, 2),
  ('cf116c2b-9b22-5343-a14e-2acaf76cefb1', 'Behavior in Class', 'Sleeping', '2a', 6, 2),
  ('7b74e41e-2929-563f-b827-15ee90d18e0c', 'Chapel', 'Computer use', '2a', 6, 2),
  ('b4e255de-1f5c-5bb6-b10c-0d0ce2327603', 'Chapel', 'Eating/Drinking', '2a', 6, 2),
  ('b4722bfb-308b-54e6-bf27-2d2f1963c5f0', 'Chapel', 'Talking', '2a', 6, 2),
  ('467335bc-4305-5e8c-ad3f-00638da0d2f7', 'Chapel', 'Sleeping', '2a', 6, 2),
  ('9b53c638-e798-568d-a7b2-eb10bc7ca89e', 'Chapel', 'Reading unauthorized material', '2a', 6, 2),
  ('6649509a-98d6-5727-8de0-0379bf8cca08', 'Study C.Q.', 'C.Q. violation', '2b', 10, 2),
  ('62fd7271-e62b-5953-ac52-393d4f31f891', 'Computers', 'AUP violation', '2a', 6, 2),
  ('1db17c33-a1da-53e8-a20e-253abd0187e4', 'Computers', 'Improper computer use', '2a', 6, 2),
  ('3b7f42a5-0803-5a4f-aa57-ce734e2aa97e', 'Computers', 'Unsecured laptop', '2a', 6, 2),
  ('6f782858-1e6a-51ec-9da0-b3b6b19511a2', 'Conduct', 'Absent any required activity', '2a', 6, 2),
  ('d6e78b18-f7b6-5ffe-90a0-7cf64e857240', 'Conduct', 'Buying/Selling Items', '2a', 6, 2),
  ('46228604-c167-578e-ae11-015a6dae35a8', 'Conduct', 'Creating a disturbance', '2a', 6, 2),
  ('82178171-c0fa-5b54-9800-31ce5f51b17c', 'Conduct', 'Horseplay', '2a', 6, 2),
  ('45b20ca9-c64b-531d-a877-2b1f8529e8c6', 'Conduct', 'Immature actions', '2a', 6, 2),
  ('999f2b91-1915-5a0b-b7fb-864603aa2605', 'Conduct', 'Improper judgment/comments', '2a', 6, 2),
  ('cc650ef7-94ea-5291-9e71-1f9a69303cf1', 'Conduct', 'Throwing snowballs (except when authorized)', '2a', 6, 2),
  ('e5e6d708-1d80-50ef-a9fc-cc1ee7004268', 'Conduct', 'Impolite behavior', '2a', 6, 2),
  ('5bb7a4ff-24f0-54c7-ad84-70c096903393', 'Duty', 'Careless performance of duty', '2a', 6, 2),
  ('e3511acd-5815-5001-a90c-8ed32a21d93e', 'Equipment/Property', 'Intentional misuse of Academy property', '2a', 6, 2),
  ('83ef636f-0236-5a6e-be9b-af3533812f85', 'Equipment/Property', 'Civilian clothes', '2a', 6, 2),
  ('c1813e6c-6751-57b7-b38f-aa556dc2e50f', 'Equipment/Property', 'Unauthorized items', '2a', 6, 2),
  ('d4b1054b-c860-5de9-b32a-4939fdbf624c', 'Equipment/Property', 'Unauthorized alteration of uniform', '2a', 6, 2),
  ('b527ca1b-8497-5658-9254-96eab650436d', 'Leaves/Day Passes', 'Improper leave or day pass procedure', '2a', 6, 2),
  ('d119f56e-3365-5e7e-b89c-5c917188a968', 'Dining Hall', 'Improper procedure', '2a', 6, 2),
  ('154d80a5-ceb4-5157-b961-78e4c8da0477', 'Dining Hall', 'Taking food or drink from the dining hall', '2a', 6, 2),
  ('6cd0e2a0-d093-52b2-a376-5b31e43cc823', 'Room/Barracks', 'Abuse of late lights', '2a', 6, 2),
  ('312ad3ad-ebab-5a4f-a722-3166fe9fe0e9', 'Room/Barracks', 'Throwing anything out of window', '2a', 6, 2),
  ('00289793-607d-5475-aea1-7a5d75bdf8fe', 'Room/Barracks', 'Unsecured room', '2a', 6, 2),
  ('42a1760b-bbc3-5a74-9fb6-fd1ad8099bb7', 'Taps', 'Light on after', '2a', 6, 2),
  ('0cba1fd3-65f2-5318-9fe5-0d8ee0fe2f13', 'Taps', 'Out of bed after', '2a', 6, 2),
  ('1018b697-d4aa-5ed5-83ae-abb9ac1eb4a9', 'Taps', 'Computer use after', '2a', 6, 2),
  ('6fcc5d86-08f8-558f-924f-c1b12afb0766', 'Arms (Rifle/Sabre)', 'Failure to report loss of', '2b', 10, 2),
  ('2b7331c8-8c17-5b17-b9a7-5d19453a1cba', 'Arms (Rifle/Sabre)', 'Misuse of', '2b', 10, 2),
  ('60a50135-e3ce-5615-9920-76362f421dd1', 'Attitude', 'Lackadaisical', '2b', 10, 2),
  ('aa029d7e-db99-562d-a37d-9e754a1a50a4', 'Conduct', 'Refusal to comply', '2b', 10, 2),
  ('81c1f895-0a27-5992-b1ed-ed87c268122d', 'Conduct', 'Improper conduct during parade', '2b', 10, 2),
  ('f52f65c8-3c2f-52d9-a73f-e3502feb10d3', 'Conduct', 'Vulgarity, profanity, lewd gesture', '2b', 10, 2),
  ('60109aa2-600b-5d08-b63e-9b87a79ead1c', 'Duty', 'Inaccurate report', '2b', 10, 2),
  ('753c5b98-8062-52fe-a21a-21563ad75a95', 'Duty', 'Neglect of duty', '2b', 10, 2),
  ('95aca1fb-e2f5-5230-896b-2e333a88e012', 'Hygiene', 'Gross personal hygiene', '2b', 10, 2),
  ('c6945466-28b0-5662-8dff-ad74b92e793c', 'Infirmary', 'Missed medication', '2b', 10, 2),
  ('bfe45120-c0e9-5f88-8b86-a18909394130', 'Off Limits', 'Off limits area on campus', '2b', 10, 2),
  ('a92a0d65-43a2-5b82-aa54-79a0524c344f', 'Room/Barracks', 'Entering/exiting through window', '2b', 10, 2),
  ('7eeabeea-f916-5764-bc45-b13c91617ead', 'Room/Barracks', 'In bed after reveille/during class day', '2b', 10, 2),
  ('94d77f7a-49c7-5b62-9995-ac1319ff2f9e', 'AWOL', 'Less than 24 hours', '3a', 15, 3),
  ('c45ba9c9-fdd3-50ac-ace0-ff59741eb235', 'AWOL', 'Over 24 hours, less than 48', '3a', 15, 3),
  ('2d0cbd47-05ca-5f83-a0ad-b6d5885f4cde', 'AWOL', 'Over 48 hours, less than 72', '3a', 15, 3),
  ('0acb6270-7e4a-5a35-b177-05b9208d882b', 'Computers', 'AUP violation (Category III)', '3a', 15, 3),
  ('886c7fcd-cbd1-5dc5-835f-04e79a7559c8', 'Computers', 'Tampering with computer in any way', '3a', 15, 3),
  ('46a131c9-e8d0-5e65-829d-cf5807a91f30', 'Conduct', 'Abuse of authority', '3a', 15, 3),
  ('7929d2cc-3306-5de0-a0d5-1e6c4a16a7df', 'Conduct', 'Unauthorized automobile in area', '3a', 15, 3),
  ('9605b226-1374-5361-93d8-7f88400dffd6', 'Conduct', 'Conduct unbecoming a cadet', '3a', 15, 3),
  ('fbf26a43-4580-5cae-82de-dfe632158b79', 'Conduct', 'Safety violation', '3a', 15, 3),
  ('3fd67254-9bb7-5374-ac8b-bccf832b0df4', 'Conduct', 'Creating/participating in a disorder', '3a', 15, 3),
  ('01162719-202f-5dbb-9eb0-660b77ffc3cf', 'Conduct', 'Disrespect to Cadet Officer/NCO', '3a', 15, 3),
  ('33db174e-0ccc-50df-bfa3-3e5a29998832', 'Conduct', 'Disrespect to Faculty Officer', '3a', 15, 3),
  ('9426cadb-842a-519a-99cc-74c8d64e64f2', 'Conduct', 'Possession/use of intoxicants', '3a', 15, 3),
  ('e7108d99-5b33-56b8-9dba-dfcd76dfbf68', 'Conduct', 'Failure to fulfill commitment', '3a', 15, 3),
  ('6401962f-3a23-56e5-8c0a-02a6400ded73', 'Conduct', 'Fighting/Striking another cadet', '3a', 15, 3),
  ('651c8399-7164-598f-bb5f-68f5523d812a', 'Conduct', 'Use/possession of fireworks/explosives', '3a', 15, 3),
  ('ea192eb4-2128-55de-bad3-7ef88306fa1c', 'Conduct', 'Indecent Exposure', '3a', 15, 3),
  ('db4750be-d34e-57ac-a93f-7703e2d1736d', 'Conduct', 'Insubordination to Cadet Officer/NCO', '3a', 15, 3),
  ('d9d95548-19ea-5b78-90b4-f4c706787e03', 'Conduct', 'Insubordination to Faculty Officer', '3a', 15, 3),
  ('7028a8e7-8fd4-5995-964c-10248e85dfe5', 'Conduct', 'Possession of Pornography', '3a', 15, 3),
  ('03a9283e-de69-558a-8c40-63141549e856', 'Conduct', 'Provoking an incident', '3a', 15, 3),
  ('9ef3239f-aaff-5692-a194-153c7ccf6738', 'Conduct', 'Reckless driving', '3a', 15, 3),
  ('fe1ce5b8-60bd-52b6-95d8-b68e34484727', 'Conduct', 'Possession/use of cell phone', '3a', 15, 3),
  ('8ed2048f-1d3c-5206-913a-52c630041a38', 'Conduct', 'Refusing to obey an order from Cadet Officer/NCO', '3a', 15, 3),
  ('572147fc-9f5a-51ed-879d-8ad540424730', 'Conduct', 'Refusing to obey an order from Faculty Officer', '3a', 15, 3),
  ('f02ba823-cd4a-578f-a680-d17e29b54667', 'Conduct', 'Direct Disobedience', '3a', 15, 3),
  ('9d574e58-b1d9-5411-98b1-cd53957bcc51', 'Conduct', 'Threatening', '3a', 15, 3),
  ('2cf64854-a941-5c1b-ab13-83d1431e36d0', 'Conduct', 'Unchaperoned female guest on campus', '3a', 15, 3),
  ('85ea7efc-4201-537b-9747-d4fdd2bdeceb', 'Duty', 'Neglect of duty (Category III)', '3a', 15, 3),
  ('c92c0a3a-d02d-5320-8eda-206bd497778f', 'Duty', 'Withholding information', '3a', 15, 3),
  ('ad815bbe-ef54-5e3b-8965-95d011605c5c', 'Equipment/Property', 'Damage/destruction of Academy property', '3a', 15, 3),
  ('430ab63b-9a37-5a2b-ad32-932fae22e1e5', 'Leaves/Day Passes', 'Late returning from leave/day pass', '3a', 15, 3),
  ('31615eee-f575-5772-b364-c43df1f21f7e', 'Leaves/Day Passes', 'Absent scheduled parade', '3a', 15, 3),
  ('31bfe285-457a-57e7-a996-9182f612ccc3', 'Dining Hall', 'Throwing food', '3a', 15, 3),
  ('69d467d9-f492-5a52-84e6-599bfa638392', 'Off-Limits', 'Any off-limits area off campus', '3a', 15, 3),
  ('ce06fcfd-7049-578e-9b6e-bbeea1e7460c', 'Room/Barracks', 'Cooking in', '3a', 15, 3),
  ('2e9f51ef-1ffe-5c3c-8082-b0ff17fe889a', 'Room/Barracks', 'In another cadet''s room, occupant not present', '3a', 15, 3),
  ('75df2423-6b71-545e-adcc-73ab22243a53', 'Taps', 'Out of barracks after', '3a', 15, 3),
  ('85ed217c-9f36-5f8d-b55f-b1bc611d5e20', 'Taps', 'Out of the company area after', '3a', 15, 3),
  ('a89c056c-f8c7-5d4e-a400-83650ca32a43', 'Tobacco', 'Distribution of nicotine/vape products', '3a', 15, 3),
  ('73ee52c9-4286-5015-80b6-31b0c0972fbd', 'Tobacco', 'Possession/use of nicotine/vape products', '3a', 15, 3),
  ('7937f84e-836c-5244-bb2a-d788a33fa672', 'Tribunal', 'AWOL Over 72 hours', '3c', 35, 3),
  ('a7c001d1-ffaf-516f-bb90-927c0f1b8308', 'Tribunal', 'Fighting/Manhandling/Physical Assault', '3c', 35, 3),
  ('7ac8d97f-face-56d7-b7b1-51dcbedc95c8', 'Tribunal', 'Possession or use of Drugs/Intoxicants/Paraphernalia', '3c', 35, 3),
  ('3245907f-7bf9-59f9-969e-3149bf37f8af', 'Tribunal', 'Sexual-related activity', '3c', 35, 3),
  ('777fe474-c88f-50c0-a825-c94d9c2a7c6a', 'Tribunal', 'Hazing', '3c', 35, 3),
  ('c747eabb-cc00-5781-93d6-954e946d3dd6', 'Tribunal', 'Inciting a riot', '3c', 35, 3),
  ('b8e6239d-c8b1-5213-a74a-0bda8df84f76', 'Honor Code Violations', 'Lying', '3c', 35, 3),
  ('0e1540b5-7095-57bd-af8f-454d70e198be', 'Honor Code Violations', 'Cheating', '3c', 35, 3),
  ('f3262e54-34e7-5446-86f7-b4ccfa5ba530', 'Honor Code Violations', 'Stealing', '3c', 35, 3),
  ('1e8eb2ca-6785-55c0-a151-74f923ef62be', 'Honor Code Violations', 'Failure to report Honor Violation', '3c', 35, 3),
  ('cffc942a-a60c-5c58-a6f0-98a1d54cc45f', 'Honor Code Violations', 'Falsifying documents', '3c', 35, 3)
ON CONFLICT (offense_group, offense_name, policy_category) DO UPDATE
SET
  offense_code = EXCLUDED.offense_code,
  demerits = EXCLUDED.demerits;

-- Remap seed/demo reports off legacy placeholder offenses
UPDATE public.demerit_reports SET offense_type_id = 'ed185f1c-fbc3-51df-a6b4-9ac6a17af619'::uuid WHERE offense_type_id = 'e0000000-0000-0000-0000-000000000001'::uuid;
UPDATE public.demerit_reports SET offense_type_id = '9984e76d-78d4-5ec0-93a9-cc285f9aba3b'::uuid WHERE offense_type_id = 'e0000000-0000-0000-0000-000000000002'::uuid;
UPDATE public.demerit_reports SET offense_type_id = '01162719-202f-5dbb-9eb0-660b77ffc3cf'::uuid WHERE offense_type_id = 'e0000000-0000-0000-0000-000000000003'::uuid;
UPDATE public.demerit_reports SET offense_type_id = '5920e46a-2383-5d44-806b-466151884f10'::uuid WHERE offense_type_id = 'e0000000-0000-0000-0000-000000000004'::uuid;
UPDATE public.demerit_reports SET offense_type_id = '4f59bb5a-9f4e-5743-9da4-a6987520d2bf'::uuid WHERE offense_type_id = 'e0000000-0000-0000-0000-000000000005'::uuid;

-- Remove legacy placeholder offenses when no longer referenced
DELETE FROM public.offense_types
WHERE id IN ('e0000000-0000-0000-0000-000000000001'::uuid, 'e0000000-0000-0000-0000-000000000002'::uuid, 'e0000000-0000-0000-0000-000000000003'::uuid, 'e0000000-0000-0000-0000-000000000004'::uuid, 'e0000000-0000-0000-0000-000000000005'::uuid)
  AND NOT EXISTS (
    SELECT 1 FROM public.demerit_reports dr WHERE dr.offense_type_id = offense_types.id
  );

COMMIT;
